repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
  - name: cowboysysop
    url: https://cowboysysop.github.io/charts/
  - name: traefik
    url: https://helm.traefik.io/traefik

environments:
  default:
    values:
    - fog.yaml

releases:
  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    version: v1.0.4
    values:
      - installCRDs: true
      - cert-manager.yaml

  - name: letsencrypt
    namespace: cert-manager
    chart: ./letsencrypt
    needs:
      - cert-manager/cert-manager
    secrets:
      - secrets.letsencrypt.yaml

  - name: metallb
    namespace: metallb-system
    chart: ./metallb
    secrets:
      - secrets.metallb.yaml

  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    values:
      - traefik.yaml.gotmpl

  - name: kubernetes-dashboard
    chart: kubernetes-dashboard/kubernetes-dashboard
    namespace: kubernetes-dashboard
    values:
      - kubernetes-dashboard.yaml.gotmpl

  - name: kubernetes-dashboard-access
    chart: ./kubernetes-dashboard-access
    namespace: kubernetes-dashboard
    createNamespace: false
    values:
      - kubernetes-dashboard-access.yaml

  - name: zorua
    namespace: zorua
    chart: ../sadm/zorua/
    values:
      - zorua.yaml
    secrets:
      - secrets.zorua.yaml

  - name: whoami
    namespace: whoami
    chart: cowboysysop/whoami
    values:
      - whoami.yaml

  - name: coredns
    chart: ../coredns-deployment/charts/coredns
    values:
      - coredns.yaml.gotmpl

