repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: jetstack
  url: https://charts.jetstack.io

releases:
  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    version: v1.0.4
    values:
      - installCRDs: true
      - cert-manager.yaml
  - name: letsencrypt
    namespace: cert-manager
    chart: ./letsencrypt
