apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: nick@chalko.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudDNS:
            # The ID of the GCP project
            project: marine-compound-291704
            # This is the secret used to access the service account
            # pass show gloud/clouddns-dns01-solver-svc-acct | \
            #   kubectl create secret generic clouddns-dns01-solver-svc-acct
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json